version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/btcwalletapi-test
    container_name: btcwalletapi-test

volumes:
  btcwalletapi-test-data: